# Generated by Django 5.1.1 on 2024-10-31 04:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="project",
            name="created_at",
        ),
        migrations.AddField(
            model_name="issue",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime(2024, 1, 1, 0, 0)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime(2024, 1, 1, 0, 0)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="due_date",
            field=models.DateField(default=datetime.datetime(2024, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="issue",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="joined_projects", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="JoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
