# Generated by Django 5.1.1 on 2024-11-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_fileupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
